# using docker in docker. It's wase to use the overlayfs driver for
# improved performance and reduce disk usage.
variables:
    DOCKER_DRIVER: overlay

before_script:
    - docker info
    - git submodule sync --recursive
    - git submodule update --init --recursive

stages:
    - build-docker-base
    - test
    - build

docker_build:
    stage: build-docker-base
    script:
      - docker build --tag mylittlepwny:build docker

mylittlepwny_build:
    stage: test
    script:
      - stack --docker build
      - stack --docker test

image_build:
    stage: build
    script:
      - stack --docker image container

